# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walmart_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
