#!/usr/bin/python

# From a result file generated by the product matching spider,
# extract products that had no matches

# The filename is given as an argument and it should be of type 2 output format

import sys

with open(sys.argv[1], "r") as filein:
    for line in filein:
        if "," not in line:
            print line.strip()


