# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitXMLItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(choices=[(b'session', b'session'), (b'basic', b'basic')], max_length=15)),
                ('status', models.CharField(choices=[(b'successful', b'successful'), (b'failed', b'failed')], db_index=True, max_length=20)),
                ('when', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('multi_item', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
