# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_errortext_itemmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmetadata',
            name='feed_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemmetadata',
            name='upc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submitxmlitem',
            name='when',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
