{"page_title": "Sophie Tufted White Faux Leather Queen-size Platform Bed", "url": "http://www.overstock.com/Home-Garden/Sophie-Tufted-White-Faux-Leather-Queen-size-Platform-Bed/6032887/product.html?IID=prod6032887&sec_iid=78176", "price": "$386.99", "rank": "10", "department": "Furniture", "date": "2013-08-02", "list_name": "Sophie Tufted White Faux Leather Queen-size Platform Bed", "product_name": "Sophie Tufted White Faux Leather Queen-size Platform Bed"}
{"page_title": "Tabouret 24-inch Metal Counter Stools (Set of 2)", "url": "http://www.overstock.com/Home-Garden/Tabouret-24-inch-Metal-Counter-Stools-Set-of-2/3879160/product.html?IID=prod3879160&sec_iid=78176", "price": "$89.99", "rank": "9", "department": "Furniture", "date": "2013-08-02", "list_name": "Tabouret 24-inch Metal Counter Stools (Set of 2)", "product_name": "Tabouret 24-inch Metal Counter Stools (Set of 2)"}
{"page_title": "Comfort Dreams Select-A-Firmness 11-inch Queen-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Comfort-Dreams-Select-A-Firmness-11-inch-Queen-size-Memory-Foam-Mattress/3158654/product.html?IID=prod3158654&sec_iid=78176", "price": "$399.99", "rank": "1", "department": "Furniture", "date": "2013-08-02", "list_name": "Comfort Dreams Select-A-Firmness 11-inch Queen-size Memory Foam Mattress", "product_name": "Comfort Dreams Select-A-Firmness 11-inch Queen-size Memory Foam Mattress"}
{"page_title": "ETHAN HOME LeAnn Graceful Scroll Bronze Iron Queen-size Poster Bed", "url": "http://www.overstock.com/Home-Garden/ETHAN-HOME-LeAnn-Graceful-Scroll-Bronze-Iron-Queen-size-Poster-Bed/4765274/product.html?IID=prod4765274&sec_iid=78176", "price": "$269.99", "rank": "7", "department": "Furniture", "date": "2013-08-02", "list_name": "ETHAN HOME LeAnn Graceful Scroll Bronze Iron Queen-size Poster Bed", "product_name": "ETHAN HOME LeAnn Graceful Scroll Bronze Iron Queen-size Poster Bed"}
{"page_title": "Valenciara Entertainment Console", "url": "http://www.overstock.com/Home-Garden/Valenciara-Entertainment-Console/5135173/product.html?IID=prod5135173&sec_iid=78176", "price": "$166.49", "rank": "6", "department": "Furniture", "date": "2013-08-02", "list_name": "Valenciara Entertainment Console", "product_name": "Valenciara Entertainment Console"}
{"page_title": "Metro Brown Faux Leather Bed", "url": "http://www.overstock.com/Home-Garden/Metro-Brown-Faux-Leather-Bed/5943110/product.html?IID=prod5943110&sec_iid=78176", "price": "$144.99", "rank": "8", "department": "Furniture", "date": "2013-08-02", "list_name": "Metro Brown Faux Leather Bed", "product_name": "Metro Brown Faux Leather Bed"}
{"page_title": "Vintage Tabouret Stacking Chair (Set of 4)", "url": "http://www.overstock.com/Home-Garden/Vintage-Tabouret-Stacking-Chair-Set-of-4/6839588/product.html?IID=prod6839588&sec_iid=78176", "price": "$219.99", "rank": "5", "department": "Furniture", "date": "2013-08-02", "list_name": "Vintage Tabouret Stacking Chair (Set of 4)", "product_name": "Vintage Tabouret Stacking Chair (Set of 4)"}
{"page_title": "Bodipedic Essentials 8-inch Queen-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Bodipedic-Essentials-8-inch-Queen-size-Memory-Foam-Mattress/6153386/product.html?IID=prod6153386&sec_iid=78176", "price": "$299.99", "rank": "11", "department": "Furniture", "date": "2013-08-02", "list_name": "Bodipedic Essentials 8-inch Queen-size Memory Foam Mattress", "product_name": "Bodipedic Essentials 8-inch Queen-size Memory Foam Mattress"}
{"page_title": "Laminated Walnut Veneer Corner Wall Mount Shelf", "url": "http://www.overstock.com/Home-Garden/Laminated-Walnut-Veneer-Corner-Wall-Mount-Shelf/6294214/product.html?IID=prod6294214&sec_iid=78176", "price": "$35.99", "rank": "4", "department": "Furniture", "date": "2013-08-02", "list_name": "Laminated Walnut Veneer Corner Wall Mount Shelf", "product_name": "Laminated Walnut Veneer Corner Wall Mount Shelf"}
{"page_title": "Slumber Solutions Gel Memory Foam 8-inch Queen-size Mattress", "url": "http://www.overstock.com/Home-Garden/Slumber-Solutions-Gel-Memory-Foam-8-inch-Queen-size-Mattress/6995871/product.html?IID=prod6995871&sec_iid=78176", "price": "$265.49", "rank": "3", "department": "Furniture", "date": "2013-08-02", "list_name": "Slumber Solutions Gel Memory Foam 8-inch Queen-size Mattress", "product_name": "Slumber Solutions Gel Memory Foam 8-inch Queen-size Mattress"}
{"page_title": "Serta 8-inch Twin Size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Serta-8-inch-Twin-Size-Memory-Foam-Mattress/4107167/product.html?IID=prod4107167&sec_iid=78176", "price": "$249.99", "rank": "6", "department": "Bedding", "date": "2013-08-02", "list_name": "Serta 8-inch Twin Size Memory Foam Mattress", "product_name": "Serta 8-inch Twin Size Memory Foam Mattress"}
{"page_title": "ETHAN HOME Giselle Black Graceful Lines Victorian Iron Metal Bed", "url": "http://www.overstock.com/Home-Garden/ETHAN-HOME-Giselle-Black-Graceful-Lines-Victorian-Iron-Metal-Bed/7720291/product.html?IID=prod7720291&sec_iid=78176", "price": "$317.99", "rank": "2", "department": "Furniture", "date": "2013-08-02", "list_name": "ETHAN HOME Giselle Black Graceful Lines Victorian Iron Metal Bed", "product_name": "ETHAN HOME Giselle Black Graceful Lines Victorian Iron Metal Bed"}
{"page_title": "Select Luxury Reversible Medium Firm 10-Inch Full-Size Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Select-Luxury-Reversible-Medium-Firm-10-Inch-Full-Size-Foam-Mattress/6373328/product.html?IID=prod6373328&sec_iid=78176", "price": "$279.99", "rank": "12", "department": "Furniture", "date": "2013-08-02", "list_name": "Select Luxury Reversible Medium Firm 10-Inch Full-Size Foam Mattress", "product_name": "Select Luxury Reversible Medium Firm 10-Inch Full-Size Foam Mattress"}
{"page_title": "Decorator 28x28-inch Euro Square Pillows (Set of 2)", "url": "http://www.overstock.com/Bedding-Bath/Decorator-28x28-inch-Euro-Square-Pillows-Set-of-2/4493223/product.html?IID=prod4493223&sec_iid=78176", "price": "$35.99", "rank": "5", "department": "Bedding", "date": "2013-08-02", "list_name": "Decorator 28x28-inch Euro Square Pillows (Set of 2)", "product_name": "Decorator 28x28-inch Euro Square Pillows (Set of 2)"}
{"page_title": "Ray-Ban Unisex RB2132 Wayfarer Fashion Sunglasses", "url": "http://www.overstock.com/Clothing-Shoes/Ray-Ban-Unisex-RB2132-Wayfarer-Fashion-Sunglasses/5173946/product.html?IID=prod5173946&sec_iid=78176", "price": "$100.99", "rank": "1", "department": "Clothing", "date": "2013-08-02", "list_name": "Ray-Ban Unisex RB2132 Wayfarer Fashion Sunglasses", "product_name": "Ray-Ban Unisex RB2132 Wayfarer Fashion Sunglasses"}
{"page_title": "Highland Mission Oak Media Stand", "url": "http://www.overstock.com/Home-Garden/Highland-Mission-Oak-Media-Stand/4334806/product.html?IID=prod4334806&sec_iid=78176", "price": "$283.00", "rank": "12", "department": "Electronics", "date": "2013-08-02", "list_name": "Highland Mission Oak Media Stand", "product_name": "Highland Mission Oak Media Stand"}
{"page_title": "Grande Hotel Collection Posture Support 14-inch King-size Trizone Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Grande-Hotel-Collection-Posture-Support-14-inch-King-size-Trizone-Memory-Foam-Mattress/6055705/product.html?IID=prod6055705&sec_iid=78176", "price": "$659.99", "rank": "12", "department": "Bedding", "date": "2013-08-02", "list_name": "Grande Hotel Collection Posture Support 14-inch King-size Trizone Memory Foam Mattress", "product_name": "Grande Hotel Collection Posture Support 14-inch King-size Trizone Memory Foam Mattress"}
{"page_title": "BasAcc Case/ Protector/ Charger/ Stylus for Amazon Kindle Fire HD", "url": "http://www.overstock.com/Electronics/BasAcc-Case-Protector-Charger-Stylus-for-Amazon-Kindle-Fire-HD/7675906/product.html?IID=prod7675906&sec_iid=78176", "price": "$12.49", "rank": "11", "department": "Electronics", "date": "2013-08-02", "list_name": "BasAcc Case/ Protector/ Charger/ Stylus for Amazon Kindle Fire HD", "product_name": "BasAcc Case/ Protector/ Charger/ Stylus for Amazon Kindle Fire HD"}
{"page_title": "Cricut Pink Expression Die Cutting Machine with 3 cartridges \"Breast Cancer Limited Edition\"", "url": "http://www.overstock.com/Crafts-Sewing/Cricut-Pink-Expression-Die-Cutting-Machine-with-3-cartridges-Breast-Cancer-Limited-Edition/7110697/product.html?IID=prod7110697&sec_iid=78176", "price": "$167.99", "rank": "10", "department": "Electronics", "date": "2013-08-02", "list_name": "Cricut Pink Expression Die Cutting Machine with 3 cartridges \"Breast Cancer Limited Edition\"", "product_name": "Cricut Pink Expression Die Cutting Machine with 3 cartridges \"Breast Cancer Limited Edition\""}
{"page_title": "Retro Phone Handset for Apple iPhone 5, 4/4S iPad 2/ iPad 3/ iPad mini", "url": "http://www.overstock.com/Electronics/Retro-Phone-Handset-for-Apple-iPhone-5-4-4S-iPad-2-iPad-3-iPad-mini/6267585/product.html?IID=prod6267585&sec_iid=78176", "price": "$7.99", "rank": "9", "department": "Electronics", "date": "2013-08-02", "list_name": "Retro Phone Handset for Apple iPhone 5, 4/4S iPad 2/ iPad 3/ iPad mini", "product_name": "Retro Phone Handset for Apple iPhone 5, 4/4S iPad 2/ iPad 3/ iPad mini"}
{"page_title": "BasAcc Leather Swivel Case for Amazon Kindle Fire HD 7-inch", "url": "http://www.overstock.com/Electronics/BasAcc-Leather-Swivel-Case-for-Amazon-Kindle-Fire-HD-7-inch/7402278/product.html?IID=prod7402278&sec_iid=78176", "price": "$7.49", "rank": "8", "department": "Electronics", "date": "2013-08-02", "list_name": "BasAcc Leather Swivel Case for Amazon Kindle Fire HD 7-inch", "product_name": "BasAcc Leather Swivel Case for Amazon Kindle Fire HD 7-inch"}
{"page_title": "BasAcc Hybrid Case for Apple iPhone 4/ 4S", "url": "http://www.overstock.com/Electronics/BasAcc-Hybrid-Case-for-Apple-iPhone-4-4S/7322770/product.html?IID=prod7322770&sec_iid=78176", "price": "$3.76", "rank": "5", "department": "Electronics", "date": "2013-08-02", "list_name": "BasAcc Hybrid Case for Apple iPhone 4/ 4S", "product_name": "BasAcc Hybrid Case for Apple iPhone 4/ 4S"}
{"page_title": "Lawrence Entertainment Center", "url": "http://www.overstock.com/Home-Garden/Lawrence-Entertainment-Center/4273819/product.html?IID=prod4273819&sec_iid=78176", "price": "$406.79", "rank": "6", "department": "Electronics", "date": "2013-08-02", "list_name": "Lawrence Entertainment Center", "product_name": "Lawrence Entertainment Center"}
{"page_title": "BasAcc Leather Case for Amazon Kindle Paperwhite", "url": "http://www.overstock.com/Electronics/BasAcc-Leather-Case-for-Amazon-Kindle-Paperwhite/7512241/product.html?IID=prod7512241&sec_iid=78176", "price": "$5.99", "rank": "7", "department": "Electronics", "date": "2013-08-02", "list_name": "BasAcc Leather Case for Amazon Kindle Paperwhite", "product_name": "BasAcc Leather Case for Amazon Kindle Paperwhite"}
{"page_title": "Matlock Modern Glass Door TV Stand", "url": "http://www.overstock.com/Home-Garden/Matlock-Modern-Glass-Door-TV-Stand/6162021/product.html?IID=prod6162021&sec_iid=78176", "price": "$201.59", "rank": "4", "department": "Electronics", "date": "2013-08-02", "list_name": "Matlock Modern Glass Door TV Stand", "product_name": "Matlock Modern Glass Door TV Stand"}
{"page_title": "Leather Case for Samsung Galaxy Tab 2 P5100/ P5110/ 10.1-inch", "url": "http://www.overstock.com/Electronics/Leather-Case-for-Samsung-Galaxy-Tab-2-P5100-P5110-10.1-inch/6986715/product.html?IID=prod6986715&sec_iid=78176", "price": "$7.49", "rank": "3", "department": "Electronics", "date": "2013-08-02", "list_name": "Leather Case for Samsung Galaxy Tab 2 P5100/ P5110/ 10.1-inch", "product_name": "Leather Case for Samsung Galaxy Tab 2 P5100/ P5110/ 10.1-inch"}
{"page_title": "Four-inch Universal Touch Screen Stylus Set (Pack of Three)", "url": "http://www.overstock.com/Electronics/Four-inch-Universal-Touch-Screen-Stylus-Set-Pack-of-Three/6470748/product.html?IID=prod6470748&sec_iid=78176", "price": "$2.99", "rank": "2", "department": "Electronics", "date": "2013-08-02", "list_name": "Four-inch Universal Touch Screen Stylus Set (Pack of Three)", "product_name": "Four-inch Universal Touch Screen Stylus Set (Pack of Three)"}
{"page_title": "MyBat Apple iPhone 4S/4 Hybrid Protector Cover", "url": "http://www.overstock.com/Electronics/MyBat-Apple-iPhone-4S-4-Hybrid-Protector-Cover/6797433/product.html?IID=prod6797433&sec_iid=78176", "price": "$4.99", "rank": "1", "department": "Electronics", "date": "2013-08-02", "list_name": "MyBat Apple iPhone 4S/4 Hybrid Protector Cover", "product_name": "MyBat Apple iPhone 4S/4 Hybrid Protector Cover"}
{"page_title": "Kamp-Rite DOUBLE Kwik Cot", "url": "http://www.overstock.com/Sports-Toys/Kamp-Rite-DOUBLE-Kwik-Cot/7666658/product.html?IID=prod7666658&sec_iid=78176", "price": "$101.99", "rank": "9", "department": "Sports", "date": "2013-08-02", "list_name": "Kamp-Rite DOUBLE Kwik Cot", "product_name": "Kamp-Rite DOUBLE Kwik Cot"}
{"page_title": "Parachute Silk Waterproof Two-person Hammock with Stuff Sack", "url": "http://www.overstock.com/Sports-Toys/Parachute-Silk-Waterproof-Two-person-Hammock-with-Stuff-Sack/4835102/product.html?IID=prod4835102&sec_iid=78176", "price": "$39.49", "rank": "11", "department": "Sports", "date": "2013-08-02", "list_name": "Parachute Silk Waterproof Two-person Hammock with Stuff Sack", "product_name": "Parachute Silk Waterproof Two-person Hammock with Stuff Sack"}
{"page_title": "Caravan Canopy Black Zero-Gravity Chairs (Pack of Two)", "url": "http://www.overstock.com/Sports-Toys/Caravan-Canopy-Black-Zero-Gravity-Chairs-Pack-of-Two/5336679/product.html?IID=prod5336679&sec_iid=78176", "price": "$101.99", "rank": "12", "department": "Sports", "date": "2013-08-02", "list_name": "Caravan Canopy Black Zero-Gravity Chairs (Pack of Two)", "product_name": "Caravan Canopy Black Zero-Gravity Chairs (Pack of Two)"}
{"page_title": "Easy Riser 25-inch Queen-size Air Bed with Built-in Pillow", "url": "http://www.overstock.com/Home-Garden/Easy-Riser-25-inch-Queen-size-Air-Bed-with-Built-in-Pillow/7232984/product.html?IID=prod7232984&sec_iid=78176", "price": "$114.99", "rank": "6", "department": "Sports", "date": "2013-08-02", "list_name": "Easy Riser 25-inch Queen-size Air Bed with Built-in Pillow", "product_name": "Easy Riser 25-inch Queen-size Air Bed with Built-in Pillow"}
{"page_title": "Swagman Park 6-bike Storage Stand", "url": "http://www.overstock.com/Sports-Toys/Swagman-Park-6-bike-Storage-Stand/2923768/product.html?IID=prod2923768&sec_iid=78176", "rank": "7", "department": "Sports", "date": "2013-08-02", "list_name": "Swagman Park 6-bike Storage Stand", "product_name": "Swagman Park 6-bike Storage Stand"}
{"page_title": "Exerpeutic 400XL Folding Semi Recumbent Exercise Bike", "url": "http://www.overstock.com/Sports-Toys/Exerpeutic-400XL-Folding-Semi-Recumbent-Exercise-Bike/5700682/product.html?IID=prod5700682&sec_iid=78176", "price": "$148.99", "rank": "10", "department": "Sports", "date": "2013-08-02", "list_name": "Exerpeutic 400XL Folding Semi Recumbent Exercise Bike", "product_name": "Exerpeutic 400XL Folding Semi Recumbent Exercise Bike"}
{"page_title": "TheraSpa 4-person Inflatable Portable Hot Tub Spa", "url": "http://www.overstock.com/Sports-Toys/TheraSpa-4-person-Inflatable-Portable-Hot-Tub-Spa/6499764/product.html?IID=prod6499764&sec_iid=78176", "price": "$494.99", "rank": "8", "department": "Sports", "date": "2013-08-02", "list_name": "TheraSpa 4-person Inflatable Portable Hot Tub Spa", "product_name": "TheraSpa 4-person Inflatable Portable Hot Tub Spa"}
{"page_title": "Caravan Canopy Blue Zero-Gravity Chairs (Pack of Two)", "url": "http://www.overstock.com/Sports-Toys/Caravan-Canopy-Blue-Zero-Gravity-Chairs-Pack-of-Two/5333767/product.html?IID=prod5333767&sec_iid=78176", "price": "$99.99", "rank": "5", "department": "Sports", "date": "2013-08-02", "list_name": "Caravan Canopy Blue Zero-Gravity Chairs (Pack of Two)", "product_name": "Caravan Canopy Blue Zero-Gravity Chairs (Pack of Two)"}
{"page_title": "Serta Raised Queen-size Airbed with Insta III AC Pump", "url": "http://www.overstock.com/Home-Garden/Serta-Raised-Queen-size-Airbed-with-Insta-III-AC-Pump/6609121/product.html?IID=prod6609121&sec_iid=78176", "price": "$119.99", "rank": "4", "department": "Sports", "date": "2013-08-02", "list_name": "Serta Raised Queen-size Airbed with Insta III AC Pump", "product_name": "Serta Raised Queen-size Airbed with Insta III AC Pump"}
{"page_title": "Ironman Gravity 4000 Inversion Table with Memory Foam", "url": "http://www.overstock.com/Sports-Toys/Ironman-Gravity-4000-Inversion-Table-with-Memory-Foam/3352203/product.html?IID=prod3352203&sec_iid=78176", "price": "$194.00", "rank": "3", "department": "Sports", "date": "2013-08-02", "list_name": "Ironman Gravity 4000 Inversion Table with Memory Foam", "product_name": "Ironman Gravity 4000 Inversion Table with Memory Foam"}
{"page_title": "Discovery Kids Cardboard Color and Play Playhouse", "url": "http://www.overstock.com/Sports-Toys/Discovery-Kids-Cardboard-Color-and-Play-Playhouse/6982020/product.html?IID=prod6982020&sec_iid=78176", "price": "$26.49", "rank": "2", "department": "Sports", "date": "2013-08-02", "list_name": "Discovery Kids Cardboard Color and Play Playhouse", "product_name": "Discovery Kids Cardboard Color and Play Playhouse"}
{"page_title": "Handmade Museum Burgundy/ Multi N. Z. Wool Rug (3'6 x 5'6)", "url": "http://www.overstock.com/Home-Garden/Handmade-Museum-Burgundy-Multi-N.-Z.-Wool-Rug-36-x-56/3003639/product.html?IID=prod3003639&sec_iid=78176", "price": "$84.99", "rank": "10", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Handmade Museum Burgundy/ Multi N. Z. Wool Rug (3'6 x 5'6)", "product_name": "Handmade Museum Burgundy/ Multi N. Z. Wool Rug (3'6 x 5'6)"}
{"page_title": "Caravan Canopy Beige Zero-Gravity Chairs (Pack of Two)", "url": "http://www.overstock.com/Sports-Toys/Caravan-Canopy-Beige-Zero-Gravity-Chairs-Pack-of-Two/5333766/product.html?IID=prod5333766&sec_iid=78176", "price": "$99.99", "rank": "1", "department": "Sports", "date": "2013-08-02", "list_name": "Caravan Canopy Beige Zero-Gravity Chairs (Pack of Two)", "product_name": "Caravan Canopy Beige Zero-Gravity Chairs (Pack of Two)"}
{"page_title": "Hand-hooked Alexa Moroccan Trellis Wool Rug (7'6 x 9'6)", "url": "http://www.overstock.com/Home-Garden/Hand-hooked-Alexa-Moroccan-Trellis-Wool-Rug-76-x-96/5777733/product.html?IID=prod5777733&sec_iid=78176", "price": "$290.69", "rank": "12", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Hand-hooked Alexa Moroccan Trellis Wool Rug (7'6 x 9'6)", "product_name": "Hand-hooked Alexa Moroccan Trellis Wool Rug (7'6 x 9'6)"}
{"page_title": "Handmade Luna Marrakesh Trellis Wool Rug (5' x 8')", "url": "http://www.overstock.com/Home-Garden/Handmade-Luna-Marrakesh-Trellis-Wool-Rug-5-x-8/6437411/product.html?IID=prod6437411&sec_iid=78176", "price": "$158.09", "rank": "11", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Handmade Luna Marrakesh Trellis Wool Rug (5' x 8')", "product_name": "Handmade Luna Marrakesh Trellis Wool Rug (5' x 8')"}
{"page_title": "Alexa 'My Soft and Plush' Shag Rug (8' x 10')", "url": "http://www.overstock.com/Home-Garden/Alexa-My-Soft-and-Plush-Shag-Rug-8-x-10/4265216/product.html?IID=prod4265216&sec_iid=78176", "price": "$199.74", "rank": "9", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Alexa 'My Soft and Plush' Shag Rug (8' x 10')", "product_name": "Alexa 'My Soft and Plush' Shag Rug (8' x 10')"}
{"page_title": "Handmade Rodeo Dr. Spheres Sage/ Ivory N.Z. Wool Rug (3'6 x 5'6)", "url": "http://www.overstock.com/Home-Garden/Handmade-Rodeo-Dr.-Spheres-Sage-Ivory-N.Z.-Wool-Rug-36-x-56/3994459/product.html?IID=prod3994459&sec_iid=78176", "price": "$92.99", "rank": "4", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Handmade Rodeo Dr. Spheres Sage/ Ivory N.Z. Wool Rug (3'6 x 5'6)", "product_name": "Handmade Rodeo Dr. Spheres Sage/ Ivory N.Z. Wool Rug (3'6 x 5'6)"}
{"page_title": "Cotton Duck Sofa Slipcover", "url": "http://www.overstock.com/Home-Garden/Cotton-Duck-Sofa-Slipcover/628264/product.html?IID=prod628264&sec_iid=78176", "price": "$56.99", "rank": "8", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Cotton Duck Sofa Slipcover", "product_name": "Cotton Duck Sofa Slipcover"}
{"page_title": "Safavieh Cozy Solid Dark Grey Shag Rug", "url": "http://www.overstock.com/Home-Garden/Safavieh-Cozy-Solid-Dark-Grey-Shag-Rug/7322535/product.html?IID=prod7322535&sec_iid=78176", "price": "$50.99", "rank": "6", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Safavieh Cozy Solid Dark Grey Shag Rug", "product_name": "Safavieh Cozy Solid Dark Grey Shag Rug"}
{"page_title": "Supreme Felted Dual Surface Rug Pad (8' x 10')", "url": "http://www.overstock.com/Home-Garden/Supreme-Felted-Dual-Surface-Rug-Pad-8-x-10/5721573/product.html?IID=prod5721573&sec_iid=78176", "price": "$56.09", "rank": "7", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Supreme Felted Dual Surface Rug Pad (8' x 10')", "product_name": "Supreme Felted Dual Surface Rug Pad (8' x 10')"}
{"page_title": "Solid Insulated Thermal Blackout Panel Pair (63-inch)", "url": "http://www.overstock.com/Home-Garden/Solid-Insulated-Thermal-Blackout-Panel-Pair-63-inch/2946006/product.html?IID=prod2946006&sec_iid=78176", "price": "$54.99", "rank": "3", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Solid Insulated Thermal Blackout Panel Pair (63-inch)", "product_name": "Solid Insulated Thermal Blackout Panel Pair (63-inch)"}
{"page_title": "Hand-hooked Alexa Moroccan Trellis Wool Rug (5' x 8')", "url": "http://www.overstock.com/Home-Garden/Hand-hooked-Alexa-Moroccan-Trellis-Wool-Rug-5-x-8/5777732/product.html?IID=prod5777732&sec_iid=78176", "price": "$147.04", "rank": "5", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Hand-hooked Alexa Moroccan Trellis Wool Rug (5' x 8')", "product_name": "Hand-hooked Alexa Moroccan Trellis Wool Rug (5' x 8')"}
{"page_title": "Grommet Top Thermal Insulated 84-inch Blackout Curtain Panel Pair", "url": "http://www.overstock.com/Home-Garden/Grommet-Top-Thermal-Insulated-84-inch-Blackout-Curtain-Panel-Pair/4359827/product.html?IID=prod4359827&sec_iid=78176", "price": "$64.99", "rank": "2", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Grommet Top Thermal Insulated 84-inch Blackout Curtain Panel Pair", "product_name": "Grommet Top Thermal Insulated 84-inch Blackout Curtain Panel Pair"}
{"page_title": "Solid Insulated Thermal Blackout 84\" Curtain Panel Pair", "url": "http://www.overstock.com/Home-Garden/Solid-Insulated-Thermal-Blackout-84-Curtain-Panel-Pair/2946005/product.html?IID=prod2946005&sec_iid=78176", "price": "$66.90", "rank": "1", "department": "Home & Garden", "date": "2013-08-02", "list_name": "Solid Insulated Thermal Blackout 84\" Curtain Panel Pair", "product_name": "Solid Insulated Thermal Blackout 84\" Curtain Panel Pair"}
{"page_title": "Miadora Sterling Silver Morganite and Diamond Ring", "url": "http://www.overstock.com/Jewelry-Watches/Miadora-Sterling-Silver-Morganite-and-Diamond-Ring/7617843/product.html?IID=prod7617843&sec_iid=78176", "price": "$96.99", "rank": "11", "department": "Watches", "date": "2013-08-02", "list_name": "Miadora Sterling Silver Morganite and Diamond Ring", "product_name": "Miadora Sterling Silver Morganite and Diamond Ring"}
{"page_title": "West Coast Jewelry Men's Brushed-and-polished Titanium Ring with Comfort-fit Band", "url": "http://www.overstock.com/Jewelry-Watches/West-Coast-Jewelry-Mens-Brushed-and-polished-Titanium-Ring-with-Comfort-fit-Band/4097266/product.html?IID=prod4097266&sec_iid=78176", "price": "$26.99", "rank": "9", "department": "Watches", "date": "2013-08-02", "list_name": "West Coast Jewelry Men's Brushed-and-polished Titanium Ring with Comfort-fit Band", "product_name": "West Coast Jewelry Men's Brushed-and-polished Titanium Ring with Comfort-fit Band"}
{"page_title": "Icz Stonez Rhodiumplated Cubic Zirconia 3ct TGW Bridal Ring Set", "url": "http://www.overstock.com/Jewelry-Watches/Icz-Stonez-Rhodiumplated-Cubic-Zirconia-3ct-TGW-Bridal-Ring-Set/6382064/product.html?IID=prod6382064&sec_iid=78176", "price": "$23.49", "rank": "10", "department": "Watches", "date": "2013-08-02", "list_name": "Icz Stonez Rhodiumplated Cubic Zirconia 3ct TGW Bridal Ring Set", "product_name": "Icz Stonez Rhodiumplated Cubic Zirconia 3ct TGW Bridal Ring Set"}
{"page_title": "Ultimate CZ Platinum over Silver Cubic Zirconia Wedding Ring Set", "url": "http://www.overstock.com/Jewelry-Watches/Ultimate-CZ-Platinum-over-Silver-Cubic-Zirconia-Wedding-Ring-Set/5318505/product.html?IID=prod5318505&sec_iid=78176", "price": "$93.99", "rank": "7", "department": "Watches", "date": "2013-08-02", "list_name": "Ultimate CZ Platinum over Silver Cubic Zirconia Wedding Ring Set", "product_name": "Ultimate CZ Platinum over Silver Cubic Zirconia Wedding Ring Set"}
{"page_title": "Men's Black-plated Tungsten Carbide Comfort Fit Band (8 mm)", "url": "http://www.overstock.com/Jewelry-Watches/Mens-Black-plated-Tungsten-Carbide-Comfort-Fit-Band-8-mm/4747377/product.html?IID=prod4747377&sec_iid=78176", "price": "$37.99", "rank": "5", "department": "Watches", "date": "2013-08-02", "list_name": "Men's Black-plated Tungsten Carbide Comfort Fit Band (8 mm)", "product_name": "Men's Black-plated Tungsten Carbide Comfort Fit Band (8 mm)"}
{"page_title": "Men's Tungsten with Black and Blue Carbon Fiber Inlay Ring (8 mm)", "url": "http://www.overstock.com/Jewelry-Watches/Mens-Tungsten-with-Black-and-Blue-Carbon-Fiber-Inlay-Ring-8-mm/5162780/product.html?IID=prod5162780&sec_iid=78176", "price": "$40.99", "rank": "6", "department": "Watches", "date": "2013-08-02", "list_name": "Men's Tungsten with Black and Blue Carbon Fiber Inlay Ring (8 mm)", "product_name": "Men's Tungsten with Black and Blue Carbon Fiber Inlay Ring (8 mm)"}
{"page_title": "Miadora Round-cut Diamond Accent High-polish Sterling Silver Ring", "url": "http://www.overstock.com/Jewelry-Watches/Miadora-Round-cut-Diamond-Accent-High-polish-Sterling-Silver-Ring/6690956/product.html?IID=prod6690956&sec_iid=78176", "price": "$45.99", "rank": "8", "department": "Watches", "date": "2013-08-02", "list_name": "Miadora Round-cut Diamond Accent High-polish Sterling Silver Ring", "product_name": "Miadora Round-cut Diamond Accent High-polish Sterling Silver Ring"}
{"page_title": "Jewelry Armoire Over the Door Mirror Cabinet", "url": "http://www.overstock.com/Home-Garden/Jewelry-Armoire-Over-the-Door-Mirror-Cabinet/3538864/product.html?IID=prod3538864&sec_iid=78176", "price": "$129.99", "rank": "4", "department": "Watches", "date": "2013-08-02", "list_name": "Jewelry Armoire Over the Door Mirror Cabinet", "product_name": "Jewelry Armoire Over the Door Mirror Cabinet"}
{"page_title": "Stainless-steel Lava LED Bracelet Watch with Digital Display", "url": "http://www.overstock.com/Jewelry-Watches/Stainless-steel-Lava-LED-Bracelet-Watch-with-Digital-Display/6204456/product.html?IID=prod6204456&sec_iid=78176", "price": "$12.39", "rank": "3", "department": "Watches", "date": "2013-08-02", "list_name": "Stainless-steel Lava LED Bracelet Watch with Digital Display", "product_name": "Stainless-steel Lava LED Bracelet Watch with Digital Display"}
{"page_title": "Tungsten Carbide Men's Black Brushed Textured Center Ring (8 mm)", "url": "http://www.overstock.com/Jewelry-Watches/Tungsten-Carbide-Mens-Black-Brushed-Textured-Center-Ring-8-mm/6484281/product.html?IID=prod6484281&sec_iid=78176", "price": "$55.99", "rank": "2", "department": "Watches", "date": "2013-08-02", "list_name": "Tungsten Carbide Men's Black Brushed Textured Center Ring (8 mm)", "product_name": "Tungsten Carbide Men's Black Brushed Textured Center Ring (8 mm)"}
{"page_title": "Memory Wire 'Sakura Flower' Pearl and Mother of Pearl Choker (Thailand)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Memory-Wire-Sakura-Flower-Pearl-and-Mother-of-Pearl-Choker-Thailand/5096736/product.html?IID=prod5096736&sec_iid=78176", "price": "$38.99", "rank": "10", "department": "Worldstock", "date": "2013-08-02", "list_name": "Memory Wire 'Sakura Flower' Pearl and Mother of Pearl Choker (Thailand)", "product_name": "Memory Wire 'Sakura Flower' Pearl and Mother of Pearl Choker (Thailand)"}
{"page_title": "Wood Rush Grass Storage Box (China)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Wood-Rush-Grass-Storage-Box-China/6483836/product.html?IID=prod6483836&sec_iid=78176", "price": "$88.00", "rank": "7", "department": "Worldstock", "date": "2013-08-02", "list_name": "Wood Rush Grass Storage Box (China)", "product_name": "Wood Rush Grass Storage Box (China) "}
{"page_title": "Double Face Sioux Floor Lamp (Colombia)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Double-Face-Sioux-Floor-Lamp-Colombia/1559502/product.html?IID=prod1559502&sec_iid=78176", "price": "$164.99", "rank": "11", "department": "Worldstock", "date": "2013-08-02", "list_name": "Double Face Sioux Floor Lamp (Colombia)", "product_name": "Double Face Sioux Floor Lamp (Colombia)"}
{"page_title": "Handmade One-inch Sterling Silver Filigree Raindrop Earrings (China)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Handmade-One-inch-Sterling-Silver-Filigree-Raindrop-Earrings-China/4798411/product.html?IID=prod4798411&sec_iid=78176", "price": "$17.99", "rank": "12", "department": "Worldstock", "date": "2013-08-02", "list_name": "Handmade One-inch Sterling Silver Filigree Raindrop Earrings (China)", "product_name": "Handmade One-inch Sterling Silver Filigree Raindrop Earrings (China)"}
{"page_title": "Reclaimed Teak Wood and Steel Bench (India)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Reclaimed-Teak-Wood-and-Steel-Bench-India/5967720/product.html?IID=prod5967720&sec_iid=78176", "price": "$401.99", "rank": "8", "department": "Worldstock", "date": "2013-08-02", "list_name": "Reclaimed Teak Wood and Steel Bench (India)", "product_name": "Reclaimed Teak Wood and Steel Bench (India)"}
{"page_title": "Men's Tungsten Carbide Brushed and Polished Beveled Edge Ring (7 mm)", "url": "http://www.overstock.com/Jewelry-Watches/Mens-Tungsten-Carbide-Brushed-and-Polished-Beveled-Edge-Ring-7-mm/5085667/product.html?IID=prod5085667&sec_iid=78176", "price": "$36.98", "rank": "1", "department": "Watches", "date": "2013-08-02", "list_name": "Men's Tungsten Carbide Brushed and Polished Beveled Edge Ring (7 mm)", "product_name": "Men's Tungsten Carbide Brushed and Polished Beveled Edge Ring (7 mm)"}
{"page_title": "12 inches Square x 20-inch Wooden Hand-carved Walnut Oil Twist Stool (Thailand)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/12-inches-Square-x-20-inch-Wooden-Hand-carved-Walnut-Oil-Twist-Stool-Thailand/5221190/product.html?IID=prod5221190&sec_iid=78176", "price": "$179.99", "rank": "9", "department": "Worldstock", "date": "2013-08-02", "list_name": "12 inches Square x 20-inch Wooden Hand-carved Walnut Oil Twist Stool (Thailand)", "product_name": "12 inches Square x 20-inch Wooden Hand-carved Walnut Oil Twist Stool (Thailand)"}
{"page_title": "Silverplated Multicolored Bead Bracelet (Kenya)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Silverplated-Multicolored-Bead-Bracelet-Kenya/5788182/product.html?IID=prod5788182&sec_iid=78176", "price": "$21.49", "rank": "6", "department": "Worldstock", "date": "2013-08-02", "list_name": "Silverplated Multicolored Bead Bracelet (Kenya)", "product_name": "Silverplated Multicolored Bead Bracelet (Kenya)"}
{"page_title": "Elegant Bougainvillea Iron Screen (Morocco)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Elegant-Bougainvillea-Iron-Screen-Morocco/2040683/product.html?IID=prod2040683&sec_iid=78176", "price": "$323.99", "rank": "5", "department": "Worldstock", "date": "2013-08-02", "list_name": "Elegant Bougainvillea Iron Screen (Morocco)", "product_name": "Elegant Bougainvillea Iron Screen (Morocco)"}
{"page_title": "Sterling Silver 'Grape Garland' Garnet Amethyst Necklace (Thailand)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Sterling-Silver-Grape-Garland-Garnet-Amethyst-Necklace-Thailand/6369733/product.html?IID=prod6369733&sec_iid=78176", "price": "$47.49", "rank": "2", "department": "Worldstock", "date": "2013-08-02", "list_name": "Sterling Silver 'Grape Garland' Garnet Amethyst Necklace (Thailand)", "product_name": "Sterling Silver 'Grape Garland' Garnet Amethyst Necklace (Thailand)"}
{"page_title": "The Borgias: The Final Season (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/The-Borgias-The-Final-Season-DVD/8017440/product.html?IID=prod8017440&sec_iid=78176", "price": "$31.69", "rank": "11", "department": "Entertainment", "date": "2013-08-02", "list_name": "The Borgias: The Final Season (DVD)", "product_name": "The Borgias: The Final Season (DVD)"}
{"page_title": "Lonely Planet Beijing (Paperback)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Lonely-Planet-Beijing-Paperback/7307069/product.html?IID=prod7307069&sec_iid=78176", "price": "$15.06", "rank": "10", "department": "Entertainment", "date": "2013-08-02", "list_name": "Lonely Planet Beijing (Paperback)", "product_name": "Lonely Planet Beijing (Paperback)"}
{"page_title": "Letters To Juliet (Blu-ray/DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Letters-To-Juliet-Blu-ray-DVD/5153060/product.html?IID=prod5153060&sec_iid=78176", "price": "$16.09", "rank": "12", "department": "Entertainment", "date": "2013-08-02", "list_name": "Letters To Juliet (Blu-ray/DVD)", "product_name": "Letters To Juliet (Blu-ray/DVD)"}
{"page_title": "Alpaca Silver Gemstone Teardrop Earrings (Mexico)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Alpaca-Silver-Gemstone-Teardrop-Earrings-Mexico/5754286/product.html?IID=prod5754286&sec_iid=78176", "price": "$21.99", "rank": "3", "department": "Worldstock", "date": "2013-08-02", "list_name": "Alpaca Silver Gemstone Teardrop Earrings (Mexico)", "product_name": "Alpaca Silver Gemstone Teardrop Earrings (Mexico) "}
{"page_title": "Handmade Rosewood Nightstand with Forged-iron Hardware (India)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Handmade-Rosewood-Nightstand-with-Forged-iron-Hardware-India/2002421/product.html?IID=prod2002421&sec_iid=78176", "price": "$188.99", "rank": "1", "department": "Worldstock", "date": "2013-08-02", "list_name": "Handmade Rosewood Nightstand with Forged-iron Hardware (India)", "product_name": "Handmade Rosewood Nightstand with Forged-iron Hardware (India)"}
{"page_title": "Red (Special Edition) (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Red-Special-Edition-DVD/5559991/product.html?IID=prod5559991&sec_iid=78176", "price": "$6.75", "rank": "9", "department": "Entertainment", "date": "2013-08-02", "list_name": "Red (Special Edition) (DVD)", "product_name": "Red (Special Edition) (DVD)"}
{"page_title": "Solid Sarong (Indonesia)", "url": "http://www.overstock.com/Worldstock-Fair-Trade/Solid-Sarong-Indonesia/4155328/product.html?IID=prod4155328&sec_iid=78176", "price": "$12.99", "rank": "4", "department": "Worldstock", "date": "2013-08-02", "list_name": "Solid Sarong (Indonesia)", "product_name": "Solid Sarong (Indonesia)"}
{"page_title": "People's Republic (Paperback)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Peoples-Republic-Paperback/7441459/product.html?IID=prod7441459&sec_iid=78176", "price": "$9.87", "rank": "8", "department": "Entertainment", "date": "2013-08-02", "list_name": "People's Republic (Paperback)", "product_name": "People's Republic (Paperback)"}
{"page_title": "The Revolution Was Televised: The Cops, Crooks, Slingers, and Slayers Who Changed TV Drama Forever (Paperback)", "url": "http://www.overstock.com/Books-Movies-Music-Games/The-Revolution-Was-Televised-The-Cops-Crooks-Slingers-and-Slayers-Who-Changed-TV-Drama-Forever-Paperback/7660155/product.html?IID=prod7660155&sec_iid=78176", "price": "$12.85", "rank": "6", "department": "Entertainment", "date": "2013-08-02", "list_name": "The Revolution Was Televised: The Cops, Crooks, Slingers, and Slayers Who Changed TV Drama Forever (Paperback)", "product_name": "The Revolution Was Televised: The Cops, Crooks, Slingers, and Slayers Who Changed TV Drama Forever (Paperback)"}
{"page_title": "Rise and Fall of Nazi Germany (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Rise-and-Fall-of-Nazi-Germany-DVD/4792874/product.html?IID=prod4792874&sec_iid=78176", "price": "$15.87", "rank": "7", "department": "Entertainment", "date": "2013-08-02", "list_name": "Rise and Fall of Nazi Germany (DVD)", "product_name": "Rise and Fall of Nazi Germany (DVD)"}
{"page_title": "The Simpsons: The Complete Fourth Season", "url": "http://www.overstock.com/Books-Movies-Music-Games/The-Simpsons-The-Complete-Fourth-Season/6579627/product.html?IID=prod6579627&sec_iid=78176", "price": "$30.73", "rank": "3", "department": "Entertainment", "date": "2013-08-02", "list_name": "The Simpsons: The Complete Fourth Season", "product_name": "The Simpsons: The Complete Fourth Season"}
{"page_title": "The Complete Idiot's Guide to Picture Puzzles (Paperback)", "url": "http://www.overstock.com/Books-Movies-Music-Games/The-Complete-Idiots-Guide-to-Picture-Puzzles-Paperback/2972267/product.html?IID=prod2972267&sec_iid=78176", "price": "$8.87", "rank": "5", "department": "Entertainment", "date": "2013-08-02", "list_name": "The Complete Idiot's Guide to Picture Puzzles (Paperback)", "product_name": "The Complete Idiot's Guide to Picture Puzzles (Paperback)"}
{"page_title": "Cheaper By The Dozen/Cheaper By the Dozen 2 (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Cheaper-By-The-Dozen-Cheaper-By-the-Dozen-2-DVD/6496612/product.html?IID=prod6496612&sec_iid=78176", "price": "$9.71", "rank": "1", "department": "Entertainment", "date": "2013-08-02", "list_name": "Cheaper By The Dozen/Cheaper By the Dozen 2 (DVD)", "product_name": "Cheaper By The Dozen/Cheaper By the Dozen 2 (DVD)"}
{"page_title": "The Banger Sisters/Great Balls Of Fire/Imagine Me & You/Kissing Jessica Stein (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/The-Banger-Sisters-Great-Balls-Of-Fire-Imagine-Me-You-Kissing-Jessica-Stein-DVD/6856167/product.html?IID=prod6856167&sec_iid=78176", "price": "$17.80", "rank": "2", "department": "Entertainment", "date": "2013-08-02", "list_name": "The Banger Sisters/Great Balls Of Fire/Imagine Me & You/Kissing Jessica Stein (DVD)", "product_name": "The Banger Sisters/Great Balls Of Fire/Imagine Me & You/Kissing Jessica Stein (DVD)"}
{"page_title": "Ron White: They Call Me \"Tater Salad\" (DVD)", "url": "http://www.overstock.com/Books-Movies-Music-Games/Ron-White-They-Call-Me-Tater-Salad-DVD/886179/product.html?IID=prod886179&sec_iid=78176", "price": "$10.75", "rank": "4", "department": "Entertainment", "date": "2013-08-02", "list_name": "Ron White: They Call Me \"Tater Salad\" (DVD)", "product_name": "Ron White: They Call Me \"Tater Salad\" (DVD)"}
{"page_title": "Burberry Giant Check Cashmere Scarf", "url": "http://www.overstock.com/Clothing-Shoes/Burberry-Giant-Check-Cashmere-Scarf/7252316/product.html?IID=prod7252316&sec_iid=78176", "price": "$299.99", "rank": "12", "department": "Clothing", "date": "2013-08-02", "list_name": "Burberry Giant Check Cashmere Scarf", "product_name": "Burberry Giant Check Cashmere Scarf"}
{"page_title": "London Fog Knightsbridge Tote Bag", "url": "http://www.overstock.com/Clothing-Shoes/London-Fog-Knightsbridge-Tote-Bag/6652205/product.html?IID=prod6652205&sec_iid=78176", "price": "$84.99", "rank": "11", "department": "Clothing", "date": "2013-08-02", "list_name": "London Fog Knightsbridge Tote Bag", "product_name": "London Fog Knightsbridge Tote Bag"}
{"page_title": "Ray-Ban Unisex Tortoise Sunglasses", "url": "http://www.overstock.com/Clothing-Shoes/Ray-Ban-Unisex-Tortoise-Sunglasses/8028460/product.html?IID=prod8028460&sec_iid=78176", "price": "$99.99", "rank": "10", "department": "Clothing", "date": "2013-08-02", "list_name": "Ray-Ban Unisex Tortoise Sunglasses", "product_name": "Ray-Ban Unisex Tortoise Sunglasses"}
{"page_title": "Rafe Women's 'Rebecca' Regular Suede Boots (Size  6.5 )", "url": "http://www.overstock.com/Clothing-Shoes/Rafe-Womens-Rebecca-Regular-Suede-Boots-Size-6.5/8223186/product.html?IID=prod8223186&sec_iid=78176", "price": "$159.99", "rank": "8", "department": "Clothing", "date": "2013-08-02", "list_name": "Rafe Women's 'Rebecca' Regular Suede Boots (Size 6.5 )", "product_name": "Rafe Women's 'Rebecca' Regular Suede Boots (Size  6.5 )"}
{"page_title": "Ray-Ban Men's 'RB2132' New Wayfarer Sunglasses", "url": "http://www.overstock.com/Clothing-Shoes/Ray-Ban-Mens-RB2132-New-Wayfarer-Sunglasses/7031048/product.html?IID=prod7031048&sec_iid=78176", "price": "$99.99", "rank": "6", "department": "Clothing", "date": "2013-08-02", "list_name": "Ray-Ban Men's 'RB2132' New Wayfarer Sunglasses", "product_name": "Ray-Ban Men's 'RB2132' New Wayfarer Sunglasses"}
{"page_title": "Grace Elements Women's Studded Tank Top", "url": "http://www.overstock.com/Clothing-Shoes/Grace-Elements-Womens-Studded-Tank-Top/6839950/product.html?IID=prod6839950&sec_iid=78176", "price": "$19.99", "rank": "5", "department": "Clothing", "date": "2013-08-02", "list_name": "Grace Elements Women's Studded Tank Top", "product_name": "Grace Elements Women's Studded Tank Top"}
{"page_title": "24/7 Comfort Apparel Women's 3/4-sleeve Tunic", "url": "http://www.overstock.com/Clothing-Shoes/24-7-Comfort-Apparel-Womens-3-4-sleeve-Tunic/6115828/product.html?IID=prod6115828&sec_iid=78176", "price": "$29.99", "rank": "7", "department": "Clothing", "date": "2013-08-02", "list_name": "24/7 Comfort Apparel Women's 3/4-sleeve Tunic", "product_name": "24/7 Comfort Apparel Women's 3/4-sleeve Tunic"}
{"page_title": "R & M Richards Women's 2-piece Mandarin Jacket Dress", "url": "http://www.overstock.com/Clothing-Shoes/R-M-Richards-Womens-2-piece-Mandarin-Jacket-Dress/8095811/product.html?IID=prod8095811&sec_iid=78176", "price": "$79.99", "rank": "4", "department": "Clothing", "date": "2013-08-02", "list_name": "R & M Richards Women's 2-piece Mandarin Jacket Dress", "product_name": "R & M Richards Women's 2-piece Mandarin Jacket Dress"}
{"page_title": "R & M Richards Women's Lace Accented Empire Dress", "url": "http://www.overstock.com/Clothing-Shoes/R-M-Richards-Womens-Lace-Accented-Empire-Dress/7894704/product.html?IID=prod7894704&sec_iid=78176", "price": "$49.99", "rank": "9", "department": "Clothing", "date": "2013-08-02", "list_name": "R & M Richards Women's Lace Accented Empire Dress", "product_name": "R & M Richards Women's Lace Accented Empire Dress"}
{"page_title": "Luxurious Egyptian Cotton Unisex Terry Bath Robe", "url": "http://www.overstock.com/Bedding-Bath/Luxurious-Egyptian-Cotton-Unisex-Terry-Bath-Robe/6632152/product.html?IID=prod6632152&sec_iid=78176", "price": "$33.99", "rank": "3", "department": "Clothing", "date": "2013-08-02", "list_name": "Luxurious Egyptian Cotton Unisex Terry Bath Robe", "product_name": "Luxurious Egyptian Cotton Unisex Terry Bath Robe"}
{"page_title": "Grande Hotel Collection Posture Support 8-inch Queen-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Grande-Hotel-Collection-Posture-Support-8-inch-Queen-size-Memory-Foam-Mattress/6055686/product.html?IID=prod6055686&sec_iid=78176", "price": "$269.99", "rank": "10", "department": "Bedding", "date": "2013-08-02", "list_name": "Grande Hotel Collection Posture Support 8-inch Queen-size Memory Foam Mattress", "product_name": "Grande Hotel Collection Posture Support 8-inch Queen-size Memory Foam Mattress"}
{"page_title": "R & M Richards Women's Cascading Ruffle Detail Dress", "url": "http://www.overstock.com/Clothing-Shoes/R-M-Richards-Womens-Cascading-Ruffle-Detail-Dress/7753098/product.html?IID=prod7753098&sec_iid=78176", "price": "$53.29", "rank": "2", "department": "Clothing", "date": "2013-08-02", "list_name": "R & M Richards Women's Cascading Ruffle Detail Dress", "product_name": "R & M Richards Women's Cascading Ruffle Detail Dress"}
{"page_title": "South Beach Queen-size Bed", "url": "http://www.overstock.com/Home-Garden/South-Beach-Queen-size-Bed/4231824/product.html?IID=prod4231824&sec_iid=78176", "price": "$287.99", "rank": "11", "department": "Bedding", "date": "2013-08-02", "list_name": "South Beach Queen-size Bed", "product_name": "South Beach Queen-size Bed"}
{"page_title": "Select Luxury Medium Firm 14-inch King-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Select-Luxury-Medium-Firm-14-inch-King-size-Memory-Foam-Mattress/5977720/product.html?IID=prod5977720&sec_iid=78176", "price": "$585.99", "rank": "9", "department": "Bedding", "date": "2013-08-02", "list_name": "Select Luxury Medium Firm 14-inch King-size Memory Foam Mattress", "product_name": "Select Luxury Medium Firm 14-inch King-size Memory Foam Mattress"}
{"page_title": "Comfort Dreams Select-A-Firmness 11-inch Full-size Memory Foam Mattress", "url": "http://www.overstock.com/Home-Garden/Comfort-Dreams-Select-A-Firmness-11-inch-Full-size-Memory-Foam-Mattress/3158653/product.html?IID=prod3158653&sec_iid=78176", "price": "$355.99", "rank": "8", "department": "Bedding", "date": "2013-08-02", "list_name": "Comfort Dreams Select-A-Firmness 11-inch Full-size Memory Foam Mattress", "product_name": "Comfort Dreams Select-A-Firmness 11-inch Full-size Memory Foam Mattress"}
{"page_title": "Priage Green Tea/ Charcoal 6-inch Full-size Memory Foam  Mattress", "url": "http://www.overstock.com/Home-Garden/Priage-Green-Tea-Charcoal-6-inch-Full-size-Memory-Foam-Mattress/6756786/product.html?IID=prod6756786&sec_iid=78176", "price": "$179.99", "rank": "7", "department": "Bedding", "date": "2013-08-02", "list_name": "Priage Green Tea/ Charcoal 6-inch Full-size Memory Foam Mattress", "product_name": "Priage Green Tea/ Charcoal 6-inch Full-size Memory Foam  Mattress"}
