{"SKU": "GX5261", "page_title": "Sea Gull Lighting Serenity 2 Light Dual Mount", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Serenity-2-Light-Dual-Mount-GX5261.html", "brand": "Sea Gull Lighting", "rank": "84", "price": "$174.00", "date": "2013-08-02", "list_name": "Serenity 2 Light Dual Mount", "product_name": "Serenity 2 Light Dual Mount", "listprice": "$196.80"}
{"SKU": "MON1659", "page_title": "Monte Carlo Fan Company Combination Frosted and Clear Crystal Accessory Glass Shade", "url": "http://www.wayfair.com/Monte-Carlo-Fan-Company-Combination-Frosted-and-Clear-Crystal-Accessory-Glass-Shade-G420-MON1659.html", "brand": "Monte Carlo Fan Company", "rank": "81", "price": "$14.25", "date": "2013-08-02", "list_name": "Combination Frosted and Clear Crystal Accessory Glass Shade", "product_name": "Combination Frosted and Clear Crystal Accessory Glass Shade", "listprice": "$21.00"}
{"SKU": "GX3271", "page_title": "Sea Gull Lighting Prairie Statement  Outdoor Wall Lantern in Antique Bronze", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Prairie-Statement-Outdoor-Wall-Lantern-in-Antique-Bronze-8513-71-GX3271.html", "brand": "Sea Gull Lighting", "rank": "83", "price": "$290.00", "date": "2013-08-02", "list_name": "Prairie Statement  Outdoor Wall Lantern in Antique Bronze", "product_name": "Prairie Statement  Outdoor Wall Lantern in Antique Bronze", "listprice": "$333.60"}
{"SKU": "MON2149", "page_title": "Monte Carlo Fan Company Ceiling Fan Wall Mounted Remote Control and Receiver", "url": "http://www.wayfair.com/Monte-Carlo-Fan-Company-Ceiling-Fan-Wall-Mounted-Remote-Control-and-Receiver-WK100-MON2149.html", "brand": "Monte Carlo Fan Company", "rank": "44", "price": "$95.42", "date": "2013-08-02", "list_name": "Ceiling Fan Wall Mounted Remote Control and Receiver", "product_name": "Ceiling Fan Wall Mounted Remote Control and Receiver", "listprice": "$166.61"}
{"SKU": "GX3396", "page_title": "Sea Gull Lighting Sebring Outdoor Wall Lantern", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sebring-Outdoor-Wall-Lantern-8871-12-GX3396.html", "brand": "Sea Gull Lighting", "rank": "42", "price": "$189.00", "date": "2013-08-02", "list_name": "Sebring Outdoor Wall Lantern", "product_name": "Sebring Outdoor Wall Lantern", "listprice": "$237.60"}
{"SKU": "LO1236", "page_title": "Kenroy Home Twigs Torchiere Table Lamp", "url": "http://www.wayfair.com/Kenroy-Home-Twigs-Torchiere-Table-Lamp-30913BRZ-LO1236.html", "brand": "Kenroy Home", "rank": "43", "price": "$61.20", "date": "2013-08-02", "list_name": "Twigs Torchiere Table Lamp", "product_name": "Twigs Torchiere Table Lamp", "listprice": "$102.00"}
{"SKU": "HD2434", "page_title": "Hinkley Lighting Virginian 2 Light Wall Sconce with Optional Shades", "url": "http://www.wayfair.com/Hinkley-Lighting-Virginian-2-Light-Wall-Sconce-with-Optional-Shades-5124PB-HD2434.html", "brand": "Hinkley Lighting", "rank": "45", "price": "$167.00", "date": "2013-08-02", "list_name": "Virginian 2 Light Wall Sconce with Optional Shades", "product_name": "Virginian 2 Light Wall Sconce with Optional Shades", "listprice": "$259.50"}
{"SKU": "GX1749", "page_title": "Sea Gull Lighting Pemberton  Vanity Light in Brushed Nickel", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Pemberton-Vanity-Light-in-Brushed-Nickel-40075-962-GX1749.html", "brand": "Sea Gull Lighting", "rank": "1", "price": "$104.00", "date": "2013-08-02", "list_name": "Pemberton  Vanity Light in Brushed Nickel", "product_name": "Pemberton  Vanity Light in Brushed Nickel", "listprice": "$117.60"}
{"SKU": "GX2179", "page_title": "Sea Gull Lighting Undercabinet Fluorescent Linear Strip  in White", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Undercabinet-Fluorescent-Linear-Strip-in-White-4975-15-GX2179.html", "brand": "Sea Gull Lighting", "rank": "47", "price": "$25.76", "date": "2013-08-02", "list_name": "Undercabinet Fluorescent Linear Strip  in White", "product_name": "Undercabinet Fluorescent Linear Strip  in White", "listprice": "$47.70"}
{"SKU": "GX3585", "page_title": "Sea Gull Lighting Sheppard Fluorescent Outdoor Wall Lantern in Textured Rust Patina - Energy Star", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sheppard-Fluorescent-Outdoor-Wall-Lantern-in-Textured-Rust-Patina-Energy-Star-8981PBLE-08-GX3585.html", "brand": "Sea Gull Lighting", "rank": "46", "price": "$61.33", "date": "2013-08-02", "list_name": "Sheppard Fluorescent Outdoor Wall Lantern in Textured Rust Patina -...", "product_name": "Sheppard Fluorescent Outdoor Wall Lantern in Textured Rust Patina - Energy Star", "listprice": "$146.10"}
{"SKU": "HD1249", "page_title": "Hinkley Lighting Atlantis Outdoor Lamp", "url": "http://www.wayfair.com/Hinkley-Lighting-Atlantis-Outdoor-Lamp-in-Titanium-1640TT-HD1249.html", "brand": "Hinkley Lighting", "rank": "41", "price": "$269.00", "date": "2013-08-02", "list_name": "Atlantis Outdoor Lamp in Titanium", "product_name": "Atlantis Outdoor Lamp", "listprice": "$418.50"}
{"SKU": "FD6425", "page_title": "Outdoor Wall Lights", "url": "http://www.wayfair.com/Craftmade-Cast-Aluminum-1-Light-Outdoor-Wall-Lantern-FD6425.html", "brand": "Craftmade", "rank": "82", "price": "$37.80", "date": "2013-08-02", "list_name": "Cast Aluminum Outdoor Wall Mount", "product_name": "Outdoor Wall Lights", "listprice": "$60.00"}
{"SKU": "GX3220", "page_title": "Sea Gull Lighting H.S.S. CO-OP  Outdoor Wall Lantern in Weathered Copper", "url": "http://www.wayfair.com/Sea-Gull-Lighting-H.S.S.-CO-OP-Outdoor-Wall-Lantern-in-Weathered-Copper-8441-44-GX3220.html", "brand": "Sea Gull Lighting", "rank": "49", "price": "$444.00", "date": "2013-08-02", "list_name": "H.S.S. CO-OP  Outdoor Wall Lantern in Weathered Copper", "product_name": "H.S.S. CO-OP  Outdoor Wall Lantern in Weathered Copper", "listprice": "$504.00"}
{"SKU": "GX5215", "page_title": "Sea Gull Lighting Centra  ADA Vanity Light in Brushed Stainless", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Centra-ADA-Vanity-Light-in-Brushed-Stainless-47142-98-GX5215.html", "brand": "Sea Gull Lighting", "rank": "50", "price": "$94.00", "date": "2013-08-02", "list_name": "Centra  ADA Vanity Light in Brushed Stainless", "product_name": "Centra  ADA Vanity Light in Brushed Stainless", "listprice": "$105.60"}
{"SKU": "GX1064", "page_title": "Sea Gull Lighting 4\" IC-Airtight Low Voltage Recessed Housing", "url": "http://www.wayfair.com/Sea-Gull-Lighting-4-IC-Airtight-Low-Voltage-Recessed-Housing-1215-GX1064.html", "brand": "Sea Gull Lighting", "rank": "48", "price": "$132.00", "date": "2013-08-02", "list_name": "4\" IC-Airtight Low Voltage Recessed Housing", "product_name": "4\" IC-Airtight Low Voltage Recessed Housing", "listprice": "$151.80"}
{"SKU": "GX3394", "page_title": "Sea Gull Lighting Sebring Outdoor Wall Lantern in Weathered Copper", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sebring-Outdoor-Wall-Lantern-in-Weathered-Copper-8870-44-GX3394.html", "brand": "Sea Gull Lighting", "rank": "8", "price": "$116.00", "date": "2013-08-02", "list_name": "Sebring Outdoor Wall Lantern in Weathered Copper", "product_name": "Sebring Outdoor Wall Lantern in Weathered Copper", "listprice": "$132.00"}
{"SKU": "GX3397", "page_title": "Sea Gull Lighting Sebring Outdoor Wall Lantern in Weathered Copper", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sebring-Outdoor-Wall-Lantern-in-Weathered-Copper-8871-44-GX3397.html", "brand": "Sea Gull Lighting", "rank": "40", "price": "$210.00", "date": "2013-08-02", "list_name": "Sebring Outdoor Wall Lantern in Weathered Copper", "product_name": "Sebring Outdoor Wall Lantern in Weathered Copper", "listprice": "$237.60"}
{"SKU": "GX3172", "page_title": "Sea Gull Lighting  Bronze Outdoor Wall Sconce", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Bronze-Outdoor-Wall-Sconce-8338-10-8339-10-GX3172.html", "brand": "Sea Gull Lighting", "rank": "37", "price": "$60.00", "date": "2013-08-02", "list_name": "Bronze Outdoor Wall Sconce", "product_name": "Bronze Outdoor Wall Sconce", "listprice": "$80.25"}
{"SKU": "GX5208", "page_title": "Sea Gull Lighting Newport  Wall Sconce in Antique Brushed Nickel", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Newport-Wall-Sconce-in-Antique-Brushed-Nickel-44484-965-GX5208.html", "brand": "Sea Gull Lighting", "rank": "38", "price": "$146.00", "date": "2013-08-02", "list_name": "Newport  Wall Sconce in Antique Brushed Nickel", "product_name": "Newport  Wall Sconce in Antique Brushed Nickel", "listprice": "$165.60"}
{"SKU": "LO2342", "page_title": "Kenroy Home Hatteras 1 Light Hanging Lantern", "url": "http://www.wayfair.com/Kenroy-Home-Hatteras-1-Light-Hanging-Lantern-90965GC-LO2342.html", "brand": "Kenroy Home", "rank": "36", "price": "$160.20", "date": "2013-08-02", "list_name": "Hatteras 1 Light Hanging Lantern", "product_name": "Hatteras 1 Light Hanging Lantern", "listprice": "$267.00"}
{"SKU": "HD1280", "page_title": "Hinkley Lighting Regal Wall Lantern", "url": "http://www.wayfair.com/Hinkley-Lighting-Regal-Wall-Lantern-1725BG-HD1280.html", "brand": "Hinkley Lighting", "rank": "39", "price": "$359.00", "date": "2013-08-02", "list_name": "Regal Wall Lantern", "product_name": "Regal Wall Lantern", "listprice": "$568.50"}
{"SKU": "RTE1109", "page_title": "Artemide Tizio Classic Table", "url": "http://www.wayfair.com/Artemide-Tizio-Classic-Table-RTE1109.html", "brand": "Artemide", "rank": "34", "price": "From $530.00", "date": "2013-08-02", "list_name": "Tizio Classic Table", "product_name": "Tizio Classic Table"}
{"SKU": "RTE1249", "page_title": "Artemide Nesso Table", "url": "http://www.wayfair.com/Artemide-Nesso-Table-RTE1249.html", "brand": "Artemide", "rank": "35", "price": "$480.00", "date": "2013-08-02", "list_name": "Nesso Table", "product_name": "Nesso Table"}
{"SKU": "FOS1098", "page_title": "Foscarini Caboche Ceiling Light", "url": "http://www.wayfair.com/Foscarini-Caboche-Ceiling-Light-138008-52-FOS1098.html", "brand": "Foscarini", "rank": "32", "price": "$1,711.00", "date": "2013-08-02", "list_name": "Caboche Ceiling Light", "product_name": "Caboche Ceiling Light"}
{"SKU": "RTL1014", "page_title": "Rotaliana Drink Floor Lamp", "url": "http://www.wayfair.com/Rotaliana-Drink-Floor-Lamp-RTL1014.html", "brand": "Rotaliana", "rank": "33", "price": "From $760.50", "date": "2013-08-02", "list_name": "Drink Floor Lamp", "product_name": "Drink Floor Lamp", "listprice": "$845.00"}
{"SKU": "GX1690", "page_title": "Sea Gull Lighting Manor House  Wall Sconce in Weathered Iron", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Manor-House-Wall-Sconce-in-Weathered-Iron-4000-07-GX1690.html", "brand": "Sea Gull Lighting", "rank": "31", "price": "$124.00", "date": "2013-08-02", "list_name": "Manor House  Wall Sconce in Weathered Iron", "product_name": "Manor House  Wall Sconce in Weathered Iron", "listprice": "$141.60"}
{"SKU": "MON1633", "page_title": "Monte Carlo Fan Company Four Speed Wall Control", "url": "http://www.wayfair.com/Monte-Carlo-Fan-Company-Four-Speed-Wall-Control-ESSWC-3-MON1633.html", "brand": "Monte Carlo Fan Company", "rank": "28", "price": "$19.95", "date": "2013-08-02", "list_name": "Four Speed Wall Control", "product_name": "Four Speed Wall Control", "listprice": "$30.00"}
{"SKU": "MON1708", "page_title": "Monte Carlo Fan Company White Opal Oval Accessory Glass Shade", "url": "http://www.wayfair.com/Monte-Carlo-Fan-Company-White-Opal-Oval-Accessory-Glass-Shade-G975-MON1708.html", "brand": "Monte Carlo Fan Company", "rank": "79", "price": "$18.05", "date": "2013-08-02", "list_name": "White Opal Oval Accessory Glass Shade", "product_name": "White Opal Oval Accessory Glass Shade", "listprice": "$27.00"}
{"SKU": "GX3341", "page_title": "Sea Gull Lighting Eternity  Wall Lantern in Brushed Nickel", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Eternity-Wall-Lantern-in-Brushed-Nickel-88116-962-GX3341.html", "brand": "Sea Gull Lighting", "rank": "30", "price": "$152.00", "date": "2013-08-02", "list_name": "Eternity  Wall Lantern in Brushed Nickel", "product_name": "Eternity  Wall Lantern in Brushed Nickel", "listprice": "$172.80"}
{"SKU": "IT3692", "page_title": "Lite Source Amber   Pendant Track Light", "url": "http://www.wayfair.com/Lite-Source-Amber-Pendant-Track-Light-KIT-2883AMB-IT3692.html", "brand": "Lite Source", "rank": "80", "price": "$158.13", "date": "2013-08-02", "list_name": "Amber   Pendant Track Light", "product_name": "Amber   Pendant Track Light", "listprice": "$274.50"}
{"SKU": "MON1284", "page_title": "Monte Carlo Fan Company Handheld Remote Control and Receiver for Ceiling Fans", "url": "http://www.wayfair.com/Monte-Carlo-Fan-Company-Handheld-Remote-Control-and-Receiver-for-Ceiling-Fans-RM-RFMC-MON1284.html", "brand": "Monte Carlo Fan Company", "rank": "27", "price": "$95.42", "date": "2013-08-02", "list_name": "Handheld Remote Control and Receiver for Ceiling Fans", "product_name": "Handheld Remote Control and Receiver for Ceiling Fans", "listprice": "$166.61"}
{"SKU": "GX3218", "page_title": "Sea Gull Lighting H.S.S. CO-OP  Outdoor Wall Lantern in Weathered Copper", "url": "http://www.wayfair.com/Sea-Gull-Lighting-H.S.S.-CO-OP-Outdoor-Wall-Lantern-in-Weathered-Copper-8440-44-GX3218.html", "brand": "Sea Gull Lighting", "rank": "29", "price": "$254.00", "date": "2013-08-02", "list_name": "H.S.S. CO-OP  Outdoor Wall Lantern in Weathered Copper", "product_name": "H.S.S. CO-OP  Outdoor Wall Lantern in Weathered Copper", "listprice": "$288.00"}
{"SKU": "MON1685", "page_title": "Monte Carlo Fan Company Frosted Bell Accessory Glass Shade with Brushed Pewter Rim", "url": "http://www.wayfair.com/Monte-Carlo-Fan-Company-Frosted-Bell-Accessory-Glass-Shade-with-Brushed-Pewter-Rim-G890-MON1685.html", "brand": "Monte Carlo Fan Company", "rank": "26", "price": "$12.35", "date": "2013-08-02", "list_name": "Frosted Bell Accessory Glass Shade with Brushed Pewter Rim", "product_name": "Frosted Bell Accessory Glass Shade with Brushed Pewter Rim", "listprice": "$18.00"}
{"SKU": "EXP1010", "page_title": "Illuminating Experiences Elf Bath Light", "url": "http://www.wayfair.com/Illuminating-Experiences-Elf-Bath-Light-ELF2l-ELF2F-EXP1010.html", "brand": "Illuminating Experiences", "rank": "77", "price": "From $290.25", "date": "2013-08-02", "list_name": "Elf Bath Light", "product_name": "Elf Bath Light", "listprice": "$387.00"}
{"SKU": "EXP1019", "page_title": "Illuminating Experiences Elf Ceiling Fixture", "url": "http://www.wayfair.com/Illuminating-Experiences-Elf-Ceiling-Fixture-ELF7-ELF8-EXP1019.html", "brand": "Illuminating Experiences", "rank": "78", "price": "From $208.50", "date": "2013-08-02", "list_name": "Elf Ceiling Fixture", "product_name": "Elf Ceiling Fixture", "listprice": "$278.00"}
{"SKU": "GX1946", "page_title": "Sea Gull Lighting Chrome Vanity Light", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Chrome-Vanity-Light-4725-05-GX1946.html", "brand": "Sea Gull Lighting", "rank": "23", "price": "$100.00", "date": "2013-08-02", "list_name": "Chrome Vanity Light", "product_name": "Chrome Vanity Light", "listprice": "$112.80"}
{"SKU": "EXP1009", "page_title": "Illuminating Experiences Elf1 Bath Light", "url": "http://www.wayfair.com/Illuminating-Experiences-Elf1-Bath-Light-ELFl-ELF1F-EXP1009.html", "brand": "Illuminating Experiences", "rank": "76", "price": "From $219.75", "date": "2013-08-02", "list_name": "Elf1 Bath Light", "product_name": "Elf1 Bath Light", "listprice": "$278.75"}
{"SKU": "HD3850", "page_title": "Hinkley Lighting Plantation Outdoor Wall Lantern", "url": "http://www.wayfair.com/Hinkley-Lighting-Plantation-Outdoor-Wall-Lantern-HD3850.html", "brand": "Hinkley Lighting", "rank": "24", "price": "$189.00", "date": "2013-08-02", "list_name": "Plantation Outdoor Wall Lantern", "product_name": "Plantation Outdoor Wall Lantern", "listprice": "$283.50"}
{"SKU": "HTF1159", "page_title": "Hunter Fans 52\" Sontera 5 Reversible Blade Ceiling Fan", "url": "http://www.wayfair.com/Hunter-Fans-52-Sontera-5-Reversible-Blade-Ceiling-Fan-22434-HTF1159.html", "brand": "Hunter Fans", "rank": "25", "price": "From $143.15", "date": "2013-08-02", "list_name": "52\" Sontera 5 Reversible Blade Ceiling Fan", "product_name": "52\" Sontera 5 Reversible Blade Ceiling Fan", "listprice": "$306.00"}
{"SKU": "LO2823", "page_title": "Kenroy Home Boulder Small Outdoor Wall Lantern", "url": "http://www.wayfair.com/Kenroy-Home-Boulder-Small-Outdoor-Wall-Lantern-70281COP-LO2823.html", "brand": "Kenroy Home", "rank": "75", "price": "$124.20", "date": "2013-08-02", "list_name": "Boulder Small Outdoor Wall Lantern", "product_name": "Boulder Small Outdoor Wall Lantern", "listprice": "$195.00"}
{"SKU": "HD2512", "page_title": "Hinkley Lighting Senator 3 Light Post Lantern", "url": "http://www.wayfair.com/Hinkley-Lighting-Senator-3-Light-Post-Lantern-2501BK-HD2512.html", "brand": "Hinkley Lighting", "rank": "74", "price": "From $349.00", "date": "2013-08-02", "list_name": "Senator 3 Light Post Lantern", "product_name": "Senator 3 Light Post Lantern", "listprice": "$568.50"}
{"SKU": "MON1715", "page_title": "Monte Carlo Fan Company White Faux Alabaster Flared Bell Accessory Glass Shade", "url": "http://www.wayfair.com/Monte-Carlo-Fan-Company-White-Faux-Alabaster-Flared-Bell-Accessory-Glass-Shade-G990-MON1715.html", "brand": "Monte Carlo Fan Company", "rank": "21", "price": "$16.15", "date": "2013-08-02", "list_name": "White Faux Alabaster Flared Bell Accessory Glass Shade", "product_name": "White Faux Alabaster Flared Bell Accessory Glass Shade", "listprice": "$24.00"}
{"SKU": "MON3516", "page_title": "Monte Carlo Fan Company Replacement Halogen Bulb", "url": "http://www.wayfair.com/Monte-Carlo-Fan-Company-Replacement-Halogen-Bulb-160-010-MON3516.html", "brand": "Monte Carlo Fan Company", "rank": "18", "price": "$12.04", "date": "2013-08-02", "list_name": "Replacement Halogen Bulb", "product_name": "Replacement Halogen Bulb"}
{"SKU": "LOP1027", "page_title": "Louis Poulsen AJ Table Lamp", "url": "http://www.wayfair.com/Louis-Poulsen-AJ-Table-Lamp-LOP1027.html", "brand": "Louis Poulsen", "rank": "73", "price": "$1,218.00", "date": "2013-08-02", "list_name": "AJ Table Lamp", "product_name": "AJ Table Lamp"}
{"SKU": "HD2461", "page_title": "Hinkley Lighting Plantation 3 Light Post Lantern", "url": "http://www.wayfair.com/Hinkley-Lighting-Plantation-3-Light-Post-Lantern-2221CB-HD2461.html", "brand": "Hinkley Lighting", "rank": "72", "price": "From $769.00", "date": "2013-08-02", "list_name": "Plantation 3 Light Post Lantern", "product_name": "Plantation 3 Light Post Lantern", "listprice": "$1,153.50"}
{"SKU": "FOS1092", "page_title": "Foscarini Havana Outdoor Floor Lamp", "url": "http://www.wayfair.com/Foscarini-Havana-Outdoor-Floor-Lamp-150003-10-FOS1092.html", "brand": "Foscarini", "rank": "20", "price": "$997.00 - $1,029.00", "date": "2013-08-02", "list_name": "Havana Outdoor Floor Lamp", "product_name": "Havana Outdoor Floor Lamp"}
{"SKU": "GX3393", "page_title": "Sea Gull Lighting Sebring Outdoor Wall Lantern", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sebring-Outdoor-Wall-Lantern-8870-12-GX3393.html", "brand": "Sea Gull Lighting", "rank": "17", "price": "$104.40", "date": "2013-08-02", "list_name": "Sebring Outdoor Wall Lantern", "product_name": "Sebring Outdoor Wall Lantern", "listprice": "$132.00"}
{"SKU": "FD6113", "page_title": "Craftmade Outdoor Wall Mount Lantern", "url": "http://www.wayfair.com/Craftmade-Outdoor-Wall-Mount-Lantern-Z103-05-FD6113.html", "brand": "Craftmade", "rank": "16", "price": "From $29.97", "date": "2013-08-02", "list_name": "Outdoor Wall Mount Lantern", "product_name": "Outdoor Wall Mount Lantern", "listprice": "$48.00"}
{"SKU": "GX4306", "page_title": "Sea Gull Lighting Fluorescent 13W PL Spiral Light Bulb with GX24q-1 Base", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Fluorescent-13W-PL-Spiral-Light-Bulb-with-GX24q-1-Base-97040-GX4306.html", "brand": "Sea Gull Lighting", "rank": "19", "price": "$8.30", "date": "2013-08-02", "list_name": "Fluorescent 13W PL Spiral Light Bulb with GX24q-1 Base", "product_name": "Fluorescent 13W PL Spiral Light Bulb with GX24q-1 Base", "listprice": "$9.60"}
{"SKU": "HD4082", "page_title": "Hinkley Lighting Park Ridge 1 Light Outdoor Post Lantern", "url": "http://www.wayfair.com/Hinkley-Lighting-Park-Ridge-1-Light-Outdoor-Post-Lantern-HD4082.html", "brand": "Hinkley Lighting", "rank": "71", "price": "From $300.00", "date": "2013-08-02", "list_name": "Park Ridge 1 Light Outdoor Post Lantern", "product_name": "Park Ridge 1 Light Outdoor Post Lantern", "listprice": "$405.00"}
{"SKU": "FOS1004", "page_title": "Foscarini Twiggy Table Lamp", "url": "http://www.wayfair.com/Foscarini-Twiggy-Table-Lamp-1590011-10-FOS1004.html", "brand": "Foscarini", "rank": "68", "price": "$1,686.00", "date": "2013-08-02", "list_name": "Twiggy Table Lamp", "product_name": "Twiggy Table Lamp"}
{"SKU": "KI6695", "page_title": "Kichler 54\" Meredith 5 Blade Ceiling Fan", "url": "http://www.wayfair.com/Kichler-54-Meredith-5-Blade-Ceiling-Fan-300004DBK-KI6695.html", "brand": "Kichler", "rank": "70", "price": "$433.80", "date": "2013-08-02", "list_name": "54\" Meredith 5 Blade Ceiling Fan", "product_name": "54\" Meredith 5 Blade Ceiling Fan", "listprice": "$688.20"}
{"SKU": "FON1057", "page_title": "FontanaArte Flute Wall Lamp", "url": "http://www.wayfair.com/FontanaArte-Flute-Wall-Lamp-3314-FON1057.html", "brand": "FontanaArte", "rank": "69", "price": "$980.00", "date": "2013-08-02", "list_name": "Flute Wall Lamp", "product_name": "Flute Wall Lamp"}
{"SKU": "FON1021", "page_title": "FontanaArte Fontana Table Lamp", "url": "http://www.wayfair.com/FontanaArte-Fontana-Table-Lamp-1853-FON1021.html", "brand": "FontanaArte", "rank": "67", "price": "From $921.16", "date": "2013-08-02", "list_name": "Fontana Table Lamp", "product_name": "Fontana Table Lamp"}
{"SKU": "GX4791", "page_title": "Sea Gull Lighting 6\" Recessed Trim in White - T24", "url": "http://www.wayfair.com/Sea-Gull-Lighting-6-Recessed-Trim-in-White-T24-1157AT-14-GX4791.html", "brand": "Sea Gull Lighting", "rank": "65", "price": "$19.00", "date": "2013-08-02", "list_name": "6\" Recessed Trim in White - T24", "product_name": "6\" Recessed Trim in White - T24", "listprice": "$21.60"}
{"SKU": "MON1650", "page_title": "Monte Carlo Fan Company Neckless Bronze Tea Stain Alabaster Bell Shaped Accessory Glass Shade", "url": "http://www.wayfair.com/Monte-Carlo-Fan-Company-Neckless-Bronze-Tea-Stain-Alabaster-Bell-Shaped-Accessory-Glass-Shade-G1047-MON1650.html", "brand": "Monte Carlo Fan Company", "rank": "13", "price": "$17.10", "date": "2013-08-02", "list_name": "Neckless Bronze Tea Stain Alabaster Bell Shaped Accessory Glass Shade", "product_name": "Neckless Bronze Tea Stain Alabaster Bell Shaped Accessory Glass Shade", "listprice": "$27.00"}
{"SKU": "GX1022", "page_title": "Sea Gull Lighting 6\" Recessed Housing Baffle Trim with White Baffle", "url": "http://www.wayfair.com/Sea-Gull-Lighting-6-Recessed-Housing-Baffle-Trim-with-White-Baffle-1126-14-GX1022.html", "brand": "Sea Gull Lighting", "rank": "15", "price": "$13.50", "date": "2013-08-02", "list_name": "6\" Recessed Housing Baffle Trim with White Baffle", "product_name": "6\" Recessed Housing Baffle Trim with White Baffle", "listprice": "$15.60"}
{"SKU": "HD1399", "page_title": "Hinkley Lighting Plantation Wall Lantern", "url": "http://www.wayfair.com/Hinkley-Lighting-Plantation-Wall-Lantern-2226CB-HD1399.html", "brand": "Hinkley Lighting", "rank": "14", "price": "$289.00", "date": "2013-08-02", "list_name": "Plantation Wall Lantern", "product_name": "Plantation Wall Lantern", "listprice": "$433.50"}
{"SKU": "GX1787", "page_title": "Sea Gull Lighting Metropolis  Wall Sconce in Brushed Nickel with a Satin Etched Glass Shade", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Metropolis-Wall-Sconce-in-Brushed-Nickel-with-a-Satin-Etched-Glass-Shade-41036-999-GX1787.html", "brand": "Sea Gull Lighting", "rank": "12", "price": "$47.00", "date": "2013-08-02", "list_name": "Metropolis  Wall Sconce in Brushed Nickel with a Satin Etched Glass...", "product_name": "Metropolis  Wall Sconce in Brushed Nickel with a Satin Etched Glass Shade", "listprice": "$52.80"}
{"SKU": "GX3392", "page_title": "Sea Gull Lighting Sebring Outdoor Flush Mount in Brushed Stainless", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sebring-Outdoor-Flush-Mount-in-Brushed-Stainless-8869-98-GX3392.html", "brand": "Sea Gull Lighting", "rank": "11", "price": "$170.00", "date": "2013-08-02", "list_name": "Sebring Outdoor Flush Mount in Brushed Stainless", "product_name": "Sebring Outdoor Flush Mount in Brushed Stainless", "listprice": "$194.40"}
{"SKU": "ELL1298", "page_title": "Elk Lighting Blackwell 8\"  Outdoor Wall Lantern in Hazelnut Bronze", "url": "http://www.wayfair.com/Elk-Lighting-Blackwell-8-Outdoor-Wall-Lantern-in-Hazelnut-Bronze-42100-1-ELL1298.html", "brand": "Elk Lighting", "rank": "66", "price": "$178.00", "date": "2013-08-02", "list_name": "Blackwell 8\"  Outdoor Wall Lantern in Hazelnut Bronze", "product_name": "Blackwell 8\"  Outdoor Wall Lantern in Hazelnut Bronze", "listprice": "$195.00"}
{"SKU": "GX3391", "page_title": "Sea Gull Lighting Sebring Outdoor Flush Mount in Weathered Copper", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sebring-Outdoor-Flush-Mount-in-Weathered-Copper-8869-44-GX3391.html", "brand": "Sea Gull Lighting", "rank": "10", "price": "$120.00", "date": "2013-08-02", "list_name": "Sebring Outdoor Flush Mount in Weathered Copper", "product_name": "Sebring Outdoor Flush Mount in Weathered Copper", "listprice": "$136.80"}
{"SKU": "GX1895", "page_title": "Sea Gull Lighting Sussex Vanity Light in Brushed Nickel", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sussex-Vanity-Light-in-Brushed-Nickel-44061-962-GX1895.html", "brand": "Sea Gull Lighting", "rank": "22", "price": "$88.00", "date": "2013-08-02", "list_name": "Sussex Vanity Light in Brushed Nickel", "product_name": "Sussex Vanity Light in Brushed Nickel", "listprice": "$100.80"}
{"SKU": "GX3395", "page_title": "Sea Gull Lighting Sebring Outdoor Wall Lantern in Brushed Stainless", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sebring-Outdoor-Wall-Lantern-in-Brushed-Stainless-8870-98-GX3395.html", "brand": "Sea Gull Lighting", "rank": "9", "price": "$158.00", "date": "2013-08-02", "list_name": "Sebring Outdoor Wall Lantern in Brushed Stainless", "product_name": "Sebring Outdoor Wall Lantern in Brushed Stainless", "listprice": "$180.00"}
{"SKU": "GX3337", "page_title": "Sea Gull Lighting Hermitage Outdoor Wall Lantern", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Hermitage-Outdoor-Wall-Lantern-88082-71-GX3337.html", "brand": "Sea Gull Lighting", "rank": "64", "price": "$228.60", "date": "2013-08-02", "list_name": "Hermitage Outdoor Wall Lantern", "product_name": "Hermitage Outdoor Wall Lantern", "listprice": "$288.00"}
{"SKU": "KI3500", "page_title": "Kichler Cottage Grove  Wall Sconce in Carre Bronze", "url": "http://www.wayfair.com/Kichler-Cottage-Grove-Wall-Sconce-in-Carre-Bronze-6857CZ-KI3500.html", "brand": "Kichler", "rank": "62", "price": "$120.00", "date": "2013-08-02", "list_name": "Cottage Grove  Wall Sconce in Carre Bronze", "product_name": "Cottage Grove  Wall Sconce in Carre Bronze", "listprice": "$180.00"}
{"SKU": "KI2945", "page_title": "Kichler Cottage Grove   Wall Sconce in Carre Bronze", "url": "http://www.wayfair.com/Kichler-Cottage-Grove-Wall-Sconce-in-Carre-Bronze-5057CZ-KI2945.html", "brand": "Kichler", "rank": "63", "price": "$240.00", "date": "2013-08-02", "list_name": "Cottage Grove   Wall Sconce in Carre Bronze", "product_name": "Cottage Grove   Wall Sconce in Carre Bronze", "listprice": "$360.00"}
{"SKU": "FD5447", "page_title": "Craftmade Double Outdoor Adjustable Floodlight", "url": "http://www.wayfair.com/Craftmade-Double-Outdoor-Adjustable-Floodlight-PH-2-FD5447.html", "brand": "Craftmade", "rank": "60", "price": "$11.52", "date": "2013-08-02", "list_name": "Double Outdoor Adjustable Floodlight", "product_name": "Double Outdoor Adjustable Floodlight", "listprice": "$16.26"}
{"SKU": "GX3390", "page_title": "Sea Gull Lighting Sebring Outdoor Flush Mount", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sebring-Outdoor-Flush-Mount-8869-12-GX3390.html", "brand": "Sea Gull Lighting", "rank": "7", "price": "$108.00", "date": "2013-08-02", "list_name": "Sebring Outdoor Flush Mount", "product_name": "Sebring Outdoor Flush Mount", "listprice": "$136.80"}
{"SKU": "GX1945", "page_title": "Sea Gull Lighting Chrome Vanity Light", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Chrome-Vanity-Light-4724-05-GX1945.html", "brand": "Sea Gull Lighting", "rank": "59", "price": "$76.00", "date": "2013-08-02", "list_name": "Chrome Vanity Light", "product_name": "Chrome Vanity Light", "listprice": "$86.40"}
{"SKU": "KI2946", "page_title": "Kichler Cottage Grove   Wall Sconce in Carre Bronze", "url": "http://www.wayfair.com/Kichler-Cottage-Grove-Wall-Sconce-in-Carre-Bronze-5058CZ-KI2946.html", "brand": "Kichler", "rank": "61", "price": "$320.00", "date": "2013-08-02", "list_name": "Cottage Grove   Wall Sconce in Carre Bronze", "product_name": "Cottage Grove   Wall Sconce in Carre Bronze", "listprice": "$480.00"}
{"SKU": "GX1752", "page_title": "Sea Gull Lighting Pemberton  Vanity Light in Brushed Nickel", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Pemberton-Vanity-Light-in-Brushed-Nickel-40076-962-GX1752.html", "brand": "Sea Gull Lighting", "rank": "6", "price": "$138.00", "date": "2013-08-02", "list_name": "Pemberton  Vanity Light in Brushed Nickel", "product_name": "Pemberton  Vanity Light in Brushed Nickel", "listprice": "$156.00"}
{"SKU": "MON1286", "page_title": "Monte Carlo Fan Company Handheld Remote Control for Ceiling Fans (Remote Only)", "url": "http://www.wayfair.com/Monte-Carlo-Fan-Company-Handheld-Remote-Control-for-Ceiling-Fans-Remote-Only-HT150-WH-MON1286.html", "brand": "Monte Carlo Fan Company", "rank": "5", "price": "$31.49", "date": "2013-08-02", "list_name": "Handheld Remote Control for Ceiling Fans (Remote Only)", "product_name": "Handheld Remote Control for Ceiling Fans (Remote Only)", "listprice": "$54.58"}
{"SKU": "GX1897", "page_title": "Sea Gull Lighting Sussex Vanity Light in Brushed Nickel", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sussex-Vanity-Light-in-Brushed-Nickel-44062-962-GX1897.html", "brand": "Sea Gull Lighting", "rank": "4", "price": "$116.00", "date": "2013-08-02", "list_name": "Sussex Vanity Light in Brushed Nickel", "product_name": "Sussex Vanity Light in Brushed Nickel", "listprice": "$132.00"}
{"SKU": "GX3400", "page_title": "Sea Gull Lighting Sheppard Large  Wall Lantern in Textured Rust Patina", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Sheppard-Large-Wall-Lantern-in-Textured-Rust-Patina-8881-08-GX3400.html", "brand": "Sea Gull Lighting", "rank": "56", "price": "$57.00", "date": "2013-08-02", "list_name": "Sheppard Large  Wall Lantern in Textured Rust Patina", "product_name": "Sheppard Large  Wall Lantern in Textured Rust Patina", "listprice": "$64.80"}
{"SKU": "GX1746", "page_title": "Sea Gull Lighting Pemberton Vanity Light in Brushed Nickel", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Pemberton-Vanity-Light-in-Brushed-Nickel-40074-962-GX1746.html", "brand": "Sea Gull Lighting", "rank": "3", "price": "$74.00", "date": "2013-08-02", "list_name": "Pemberton Vanity Light in Brushed Nickel", "product_name": "Pemberton Vanity Light in Brushed Nickel", "listprice": "$84.00"}
{"SKU": "GX6157", "page_title": "Sea Gull Lighting Parkview  Vanity Light  in Antique Brushed Nickel", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Parkview-Vanity-Light-in-Antique-Brushed-Nickel-44381-965-GX6157.html", "brand": "Sea Gull Lighting", "rank": "57", "price": "$170.00", "date": "2013-08-02", "list_name": "Parkview  Vanity Light  in Antique Brushed Nickel", "product_name": "Parkview  Vanity Light  in Antique Brushed Nickel", "listprice": "$192.00"}
{"SKU": "KI4082", "page_title": "Kichler Cans and Bullets Outdoor Wall Lantern", "url": "http://www.wayfair.com/Kichler-Cans-and-Bullets-Outdoor-Wall-Lantern-9244AZ-KI4082.html", "brand": "Kichler", "rank": "2", "price": "$86.00", "date": "2013-08-02", "list_name": "Cans and Bullets Outdoor Wall Lantern", "product_name": "Cans and Bullets Outdoor Wall Lantern", "listprice": "$129.00"}
{"SKU": "LO3892", "page_title": "Kenroy Home Chesapeake Bankers Table Lamp", "url": "http://www.wayfair.com/Kenroy-Home-Chesapeake-Bankers-Table-Lamp-20610ORB-LO3892.html", "brand": "Kenroy Home", "rank": "55", "price": "$106.20", "date": "2013-08-02", "list_name": "Chesapeake Bankers Table Lamp", "product_name": "Chesapeake Bankers Table Lamp", "listprice": "$174.00"}
{"SKU": "GX5563", "page_title": "Sea Gull Lighting Ambiance Transitions Butterscotch  Wall Sconce", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Ambiance-Transitions-Butterscotch-Wall-Sconce-94112-6037-GX5563.html", "brand": "Sea Gull Lighting", "rank": "54", "price": "$80.00", "date": "2013-08-02", "list_name": "Ambiance Transitions Butterscotch  Wall Sconce", "product_name": "Ambiance Transitions Butterscotch  Wall Sconce", "listprice": "$91.20"}
{"SKU": "GX1024", "page_title": "Sea Gull Lighting 6\" Incandescent IC Airtight Recessed  Housing", "url": "http://www.wayfair.com/Sea-Gull-Lighting-6-Incandescent-IC-Airtight-Recessed-Housing-1128-GX1024.html", "brand": "Sea Gull Lighting", "rank": "53", "price": "$30.00", "date": "2013-08-02", "list_name": "6\" Incandescent IC Airtight Recessed  Housing", "product_name": "6\" Incandescent IC Airtight Recessed  Housing", "listprice": "$34.80"}
{"SKU": "GX1829", "page_title": "Sea Gull Lighting Traditional  Wall Sconce in Polished Brass", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Traditional-Wall-Sconce-in-Polished-Brass-4179-02-GX1829.html", "brand": "Sea Gull Lighting", "rank": "52", "price": "$110.00", "date": "2013-08-02", "list_name": "Traditional  Wall Sconce in Polished Brass", "product_name": "Traditional  Wall Sconce in Polished Brass", "listprice": "$132.00"}
{"SKU": "GX5564", "page_title": "Sea Gull Lighting Rustica  Wall Sconce in Antique Bronze", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Rustica-Wall-Sconce-in-Antique-Bronze-94112-619-GX5564.html", "brand": "Sea Gull Lighting", "rank": "51", "price": "$90.00", "date": "2013-08-02", "list_name": "Rustica  Wall Sconce in Antique Bronze", "product_name": "Rustica  Wall Sconce in Antique Bronze", "listprice": "$103.20"}
{"SKU": "GX1785", "page_title": "Sea Gull Lighting Metropolis Wall Sconce in Brushed Nickel", "url": "http://www.wayfair.com/Sea-Gull-Lighting-Metropolis-Wall-Sconce-in-Brushed-Nickel-41035-962-GX1785.html", "brand": "Sea Gull Lighting", "rank": "58", "price": "$44.50", "date": "2013-08-02", "list_name": "Metropolis Wall Sconce in Brushed Nickel", "product_name": "Metropolis Wall Sconce in Brushed Nickel", "listprice": "$50.40"}
